spring:
  application:
    name: simple-api
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
      jdbc:
        lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true